// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorAppForms.Server.Data;

public partial class Customer
{
    public Customer()
    {
        CustomerLocation = new HashSet<CustomerLocation>();
    }

    public int IdCustomer { get; set; }
    public string Name { get; set; }
    public DateTime Birth { get; set; }

    public virtual ICollection<CustomerLocation> CustomerLocation { get; set; }
}