// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
#nullable disable
using System;
using System.Collections.Generic;

namespace BlazorAppForms.Shared;

public sealed class CustomerLocationTransport : TransportBase
{
    public int IdCustomerLocation { get; set; }
    public int IdCustomer { get; set; }
    public string Street { get; set; }
    public short Portal { get; set; }
}